### ISSUE TITLE
Use multipart upload for VM images on AWS

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#150]
In order to verify the release scripts the developers created a sample release with 
```shell
poetry run python exasol/ds/sandbox/main.py \
     start-test-release-build \
     --aws-profile ci4_mfa \
     --release-title "experiment-240130" \
     --branch "feature/#255-Rename_data_science_sandbox_to_exasol-ai-lab"
```

... the release scripts failed with 
> botocore.exceptions.ClientError: 
> An error occurred (InvalidRequest) when calling the CopyObject operation: 
> The specified copy source is larger than the maximum allowable size for a copy source: 5.368.709.120

in exasol/ai-lab/exasol/ds/sandbox/lib/aws_access/aws_access.py", line 420, in copy_s3_object

(see [codebuild log](https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/561494727831/projects/DataScienceSandboxReleaseCo-mAfoX9WSQxF3/build/DataScienceSandboxReleaseCo-mAfoX9WSQxF3%3A5a278dbe-0ade-4d61-9682-97f4de1c2377/?region=eu-central-1)).

Analysis showed that the size of the created VM images increased from 3.9 GB to ~ 5.4 GB compared to successful verifications [some months ago](https://github.com/exasol/ai-lab/releases). 

see https://docs.aws.amazon.com/AmazonS3/latest/userguide/CopyingObjectsMPUapi.html

API
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/upload_part_copy.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/create_multipart_upload.html

**Comment by tkilias** [comment]
The easiest way is probably S3Transfer

 https://stackoverflow.com/a/43788985
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html

**Comment by ckunki** [comment]
The page at the link [s3.html](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/customizations/s3.html) above says
> Variants have also been injected into S3 client, Bucket and Object. 
> You don’t have to use S3Transfer.upload_file() directly.
