### ISSUE TITLE
Starting Docker-DB from Jupyter Notebook fails

### ISSUE THREAD

**Issue by kaklakariada** [exasol/ai-lab#180]
After starting AI-Lab with the recommended command

```sh
$ docker run \
  --volume ailab-volume:/root/notebooks \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --publish 0.0.0.0:49494:49494 \
  exasol/ai-lab:0.1.0
```

and following the `main_config` notebook, starting DockerDB with command `display(get_start_docker_db_ui())` fails after some time with the following error:
![image](https://github.com/exasol/ai-lab/assets/4711730/c64402b1-21ba-462a-abae-45f4f5120b95)

Additionally the notebook tries to start outdated Exasol version 8.18.1.

OS: Ubuntu 23.10 with latest updates installed.

**Comment by tkilias** [comment]
thanks for testing @kaklakariada , but you didn't mount the docker socket, we improved the user guide, that this hopefully get more obvious.
