### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by tkilias** [exasol/ai-lab#191]
- Improve the text in the Readme, the text will be delivered by PM
- Add Screenshot

**Comment by ckunki** [comment]
There are also some findings by @kaklakariada see IntRef.
One finding is 
> User manual is too complex,   Proposal: add section "in a nutshell"

**Comment by ThomasBestfleisch** [comment]
Please find below the suggested text for README -> Overview Section: 

Certainly! Here’s the reformatted introduction for the Exasol AI-Lab in markdown:

The Exasol AI-Lab is a pre-configured container designed to empower data scientists. It streamlines common data science and AI tasks, including data loading, preparation, exploration, model training, and deployment. Whether you’re a seasoned practitioner or just getting started, the AI-Lab provides a hassle-free experience.

# Key Features:

- Jupyter Notebook Environment: The heart of the AI-Lab is a robust Jupyter Notebook environment. It’s where you’ll work on your data science projects.

- Exasol Integration: Leverage Exasol’s power for your AI and machine learning use cases. The AI-Lab includes essential Exasol packages, extensions, and configuration tasks.

- Example Notebooks: Jumpstart your work with ready-to-use example notebooks. Explore classic machine learning scenarios (think scikit-learn), seamlessly integrate Exasol with AWS Sagemaker, and tap into Huggingface models directly within Exasol.

Feel free to explore the Exasol AI-Lab and unleash your data science potential!

**Comment by ThomasBestfleisch** [comment]
Regarding the screenshot I would suggest to simply put a screenshot from the transformers-extension notebook

**Comment by ckunki** [comment]
Many thanks to @ThomasBestfleisch for updated content of README.
I already added the change to PR #208.
