### ISSUE TITLE
Examine write access to BucketFS

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#196]
### Background and scenario 

PM tried out the AI-Lab using 
* MacOS
* Oracle Virtual Box
* AI-Lab's VMDK image (VM Edition)
* Exasol DB in demodb.exasol.com

See [Confluence](https://exasol.atlassian.net/wiki/spaces/InTeam/pages/556105786/Feedback+from+PM).

### Problem

AI-Lab failed to write files to BucketFS.

```shell
curl https://demodb.exasol.com:2202
```

* Both commands require VPN to be active
* demodb seems to use a valid certificate from let’s encrypt 

[bucketfs-python](https://github.com/exasol/bucketfs-python) seems to be able to write to the bucket

**Comment by ckunki** [comment]
According to @ahsimb the AI-Lab is hard-coded to always use HTTP only.
In contrast the demodb only supports HTTPS connections.

**Comment by ckunki** [comment]
For development and testing with Docker-DB and ITDE we need to make the Docker-DB expose the HTTPS port.

**Comment by Nicoretti** [comment]
Time: ~1d

**Comment by tkilias** [comment]
We solved the issue for certificates from trusted CA. The fix for self-signed certificates takes longer and will be tracked in https://github.com/exasol/ai-lab/issues/218
