### ISSUE TITLE
Update dependency ecdsa as soon as available

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#207]
Dependabot reports vulnerability in dependency `ecdsa`, version &le; `0.18.0`: https://github.com/exasol/ai-lab/security/dependabot/24. `ecdsa` is a transitive dependency required by `python-jose` required by `localstack-ext` required by  `localstack`.

As soon as a patched version of `ecdsa` > `0.18.0` is available the current ticket requests to update the dependency.

On the other hand `localstack` is only used for tests and does not affect the product built by this project and deployed to end users.

Availability: 

| Dependency | Currently used version | Latest  available | 
|---|---|--- | 
| localstack | [3.2.0](https://github.com/exasol/ai-lab/blob/main/poetry.lock#L1011) | [3.3.0](https://pypi.org/project/localstack/#history) |
| python-jose | [3.3.0](https://github.com/exasol/ai-lab/blob/main/poetry.lock#L886) | [3.3.0](https://pypi.org/project/python-jose/#history)  | 
| ecdsa | [0.18.0](https://github.com/exasol/ai-lab/blob/main/poetry.lock#L626) | [0.18.0](https://pypi.org/project/ecdsa/#history)  |

**Comment by redcatbear** [comment]
Checked availability today: https://pypi.org/project/ecdsa/#history
Nothing new yet unfortunately.

**Comment by redcatbear** [comment]
There is a new version of EDCSA: 
![image](https://github.com/exasol/ai-lab/assets/584162/1e795c4d-1e22-449e-89bf-5fe4b78b2c93)

But localstack has not been updated yet.
