### ISSUE TITLE
CLI: setup-vm-bucket-waf: default value for cli option allowed-ip

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#21]
DSS stores AMI images in an publicly accessible AWS S3 bucket.  In case of automated downloads Exasol company faces the risk of significant costs as AMI images are quite large (n GB).

To avoid this risk the S3 bucket is protected by a wab application firewall (WAF) which asks the downloader to solve a captcha. This should prevent at least simple implementations of automated downloaders.

According to [AWS documentation](https://docs.aws.amazon.com/waf/latest/developerguide/how-aws-waf-works-resources.html) WAF with captcha is only supported for region `us-east-1` (N. Virginia), which should be covered already by default setting for `waf_region` in file `exasol/ds/sandbox/lib/config.py`.

Additionally DSS does not require any access to the S3 bucket without WAF but AWS CLI requires to specify at least one ip address to be excluded.

```shell
poetry install # if you modified the template
export AWS_DEFAULT_REGION=us-east-1
poetry run exasol/ds/sandbox/main.py setup-vm-bucket-waf --allowed-ip 127.0.0.1
poetry run exasol/ds/sandbox/main.py setup-vm-bucket --aws-profile ci4_mfa
```

The current ticket therefore asks to
1. Enhance the DSS developer guide to describe the region restriction and how to handle it
2. Add a default value to CLI option `--allowed-ip` of DSS command `setup-vm-bucket-waf`

Current implementation:

```python
@click.option('--allowed-ip', type=str)
```

Proposal:

```python
@click.option('--allowed-ip', type=str, default="127.0.0.1", show_default=True)
```

See https://click.palletsprojects.com/en/8.1.x/options/

**Comment by tkilias** [comment]
was already solved in https://github.com/exasol/ai-lab/pull/311
