### ISSUE TITLE
Setup Azure Nested Visualization with Virtual Box

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#210]
Ticket #219 requested to describe setting up Oracle Virtual Box on Windows. 

In order to enable developers to reproduce potential future issues regarding this scenario and also to potentially update the user guide and/or screen shots the current ticket requests to create and maintain an [Azure setup](https://azure.microsoft.com/de-de/blog/nested-virtualization-in-azure/) for this scenario.

**Comment by tkilias** [comment]
It depends on Setup Azure Nested Visualization with Virtual Box.
https://azure.microsoft.com/de-de/blog/nested-virtualization-in-azure/
