### ISSUE TITLE
User Guide: Setting Up AI Lab using Virtual Box

### ISSUE THREAD

**Issue by ThomasBestfleisch** [exasol/ai-lab#219]
Please add a step-by-step guide for using VMDK on Oracle Virtual Box incl. using the following screenshots:
* Assigning an ip address and making it accessible from the host
* forwarding the port of the jupyter service

![Exasol-AI-Lab-VirtualBox-Create-Virtual-Machine-1](https://github.com/exasol/ai-lab/assets/13940266/7b6bc0ce-af0f-43f0-8f76-ab9256dc9da7)

![Exasol-AI-Lab-VirtualBox-Create-Virtual-Machine-2](https://github.com/exasol/ai-lab/assets/13940266/0cd4858b-a08c-46ae-91ca-4734ed708bb6)

![Exasol-AI-Lab-VirtualBox-Create-Virtual-Machine-3](https://github.com/exasol/ai-lab/assets/13940266/1d6e42c1-3c2a-4ac9-8608-5687be3eb403)

![Exasol-AI-Lab-VirtualBox-Create-Virtual-Machine-4](https://github.com/exasol/ai-lab/assets/13940266/83f8a6d3-eb06-4110-9bb4-c0345837b56e)

![Exasol-AI-Lab-VirtualBox-Network-Add-Portforwarding](https://github.com/exasol/ai-lab/assets/13940266/e3987d47-d54d-417a-9067-63a826e98e29)

![Exasol-AI-Lab-Jupyter](https://github.com/exasol/ai-lab/assets/13940266/3eb5acf1-affd-4cfc-aaef-00169abdc76e)

**Comment by ckunki** [comment]
@tkilias proposes to first ensure to have setups for Virtual Box, Windows, MacOSX.

Rationale: 
In general, the developers don't only need screenshots once but much more, they need to be able to reproduce, investigate, and if possible _fix_ customer issues on the systems listed above.
