### ISSUE TITLE
main_config.ipynb: Use database default port 8563

### ISSUE THREAD

**Issue by ThomasBestfleisch** [exasol/ai-lab#220]
Please set 8563 as the Port in Database Connection
<img width="184" alt="image" src="https://github.com/exasol/ai-lab/assets/13940266/81d3a21b-e57a-41f9-a866-799410efa5a9">

For BucketFS it is common to use 2580 at least if you look around in the documentation (e.g. https://docs.exasol.com/db/latest/administration/on-premise/manage_network/system_network_settings.htm)  
however it might be even better to leave the field empty instead of setting 6666

**Comment by tkilias** [comment]
We probably should also change the bucketfs port
