### ISSUE TITLE
te_init.ipynb: Can't deploy without having CREATE SCHEMA privileges

### ISSUE THREAD

**Issue by ThomasBestfleisch** [exasol/ai-lab#222]
The schema exists, but the user doesn't have the privileges to create a schema: 

`
WARNING:exasol_transformers_extension.deployment.scripts_deployer:Could not create schema EXASOL_TB. Got error: 
(
    message     =>  insufficient privileges for creating schema (Session: 1791518209485701122)
    dsn         =>  
    user        =>  EXASOL_TB
    schema      =>  
    session_id  =>  1791518209485701122
    code        =>  42500
    query       =>  CREATE SCHEMA IF NOT EXISTS EXASOL_TB
)

---------------------------------------------------------------------------
ExaQueryError                             Traceback (most recent call last)
Cell In[3], line 3
      1 from exasol.nb_connector.transformers_extension_wrapper import initialize_te_extension
----> 3 initialize_te_extension(ai_lab_config)`

**Comment by tkilias** [comment]
hm, I thought we had fixed that, I will have a look

**Comment by tkilias** [comment]
The warning is intended. If we want to disable the warning, then it is a feature.

https://github.com/exasol/transformers-extension/blob/9551f9451bc24b6f813827d3c241ba82d743de27/exasol_transformers_extension/deployment/scripts_deployer.py#L22

**Comment by redcatbear** [comment]
@ahsimb , please retest next Kehrwoche.

**Comment by ckunki** [comment]
Potentially fixed but could not proof.
