### ISSUE TITLE
Update description on hub.docker.com

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#226]
The current ticket requests to update the description on [hub.docker.com](https://hub.docker.com/r/exasol/ai-lab).

### Acceptance criteria
Please note: Max 100 characters are supported. 

* [x] command `docker pull exasol/ai-lab` in description fails: Fixed by [#223](223)
* [x] AI-Lab user guide is linked 
* [ ] (some thing else?) 

### Delimitation 

The current description names the following command which fails as reported by Dirk B.
```
docker pull exasol/ai-lab
```
![image](https://github.com/exasol/ai-lab/assets/81821845/660acec1-149d-4b56-b8e3-59bf5995bb94)

Unfortunately, this cannot be changed but will be fixed in #223

**Comment by tkilias** [comment]
I care more about the empty overview on docker hub we should link to the user guide. The pull command, we can't change. That needs to be fixed #223

**Comment by ckunki** [comment]
Hello @tkilias : I added a description and an overview, see here: [docker.com](https://hub.docker.com/repository/docker/exasol/ai-lab/general)
| | Description | Overview |
|--|--|--|
| Length limit | max. 100 characters | -- |
| Links clickable? | :x: No | ✅  Yes |
