### ISSUE TITLE
Investigate the delay between the call starting ITDE returns and the Docker DB becomes connectable

### ISSUE THREAD

**Issue by ahsimb** [exasol/ai-lab#260]
Apparently, there is 10-20 seconds delay.

At the very least this should be documented. Ideally, we should implement some sort of status pinging and display an hourglass until the DB becomes connectable.

**Comment by redcatbear** [comment]
@ahsimb , please retest this and close if the problem does not persist anymore.
Otherwise, please elaborate situation in detail. @tkilias and @ckunki both think this should not be possible.

**Comment by ahsimb** [comment]
Yes, this is something we don't see now.
