### ISSUE TITLE
Setup Azure Nested Visualization with Windows and Docker Desktop

### ISSUE THREAD

**Issue by tkilias** [exasol/ai-lab#275]
We, currently, have no way to test the AI-Lab Docker Edition with Docker Desktop on Windows.

In order to enable developers to reproduce potential future issues regarding this scenario and also to potentially update the user guide and/or screen shots the current ticket requests to create and maintain an [Azure setup](https://azure.microsoft.com/de-de/blog/nested-virtualization-in-azure/) for this scenario.

**Comment by redcatbear** [comment]
Shelve until a customer explicitly requires this kind of support.
