### ISSUE TITLE
Migrate to new S3 Bucket for Example Data

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#322]
In the past @ahsimb created an experimental bucket called `us-flight-info`.
Now, after implementing ticket #301, the AI Lab supports creating a new s3 Bucket "Example Data".

The current ticket requests to 
* [x] update the URL in the related IBIS notebook: [flight_utils.ipynb](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/data/utils/flight_utils.ipynb) and
* [x] copy the files from the old bucket to the new one, and
* Finally delete the old bucket:
  * [x] Disable related Cloudfront distribution
  * [x] Delete related Cloudfront distribution
  * [x] Delete Origin Access Control of CF Distribution
  * [x] Empty the bucket, i.e. delete all contained folders and files
  * [x] Delete the bucket

Currently we decided to move the files into a subfolder
* `<URL>/ai_lab/flight-info/`
* E.g. `<URL>/ai_lab/flight-info/US_AIRLINES.csv`

**Comment by redcatbear** [comment]
This is merged already. @tkilias will remove the S3 bucket when ready.
