### ISSUE TITLE
DNS resolution in ITDE not working in docker-db

### ISSUE THREAD

**Issue by tomuben** [exasol/ai-lab#335]
DNS resolution is not working on Github tests, see
https://github.com/exasol/ai-lab/actions/runs/11230524435/job/31613541033

See also https://github.com/exasol/notebook-connector/issues/139

**Comment by tomuben** [comment]
##RCA
This is caused by new usage of Options in pytest-plugin. 
The way how the ITDE is started differs between the Jupyter notebook tests and the real UI: In case of the tests, `pytest-plugins is used.
The default nameserver for the itde-nameserver option is empty, check https://github.com/exasol/pytest-plugins/blob/f158045b3045f9065d9d8ce0c16aad3f3806d941/pytest-backend/exasol/pytest_backend/itde.py#L142

The nameserver must be explicitly set on the CLI.

**Comment by ckunki** [comment]
Proposal: Add CLI option `--nameserver 8.8.8.8,1.1.1.1,208.67.222.222` to [test_notebooks_in_dss_docker_image.py](https://github.com/exasol/ai-lab/blob/main/test/notebook_test_runner/test_notebooks_in_dss_docker_image.py#L84)
