### ISSUE TITLE
Use a non-root user to run Jupyter in the Docker Image

### ISSUE THREAD

**Issue by tkilias** [exasol/ai-lab#66]
Security best practices recommend not to run services in Docker with root. We should prepare a non-root user which is used to run Jupyter.

https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-2-set-a-user

In total we will need two users besides `root`
* User with `sudo` permission  used for Ansible installation using `sudo` where required.
  * name `ansible` for Docker Edition
  * name `ubuntu` AMI and VM images
* User `jupyter` without `sudo` permission useds for running the docker container and Jupyterlab.

**Comment by ckunki** [comment]
https://stackoverflow.com/questions/52070171: `cat Dockerfile`

```
FROM ubuntu:latest
RUN useradd -r sathya
USER sathya
```

**Comment by ckunki** [comment]
Remark: command `sudo` is currently not installed in Docker container

**Comment by ckunki** [comment]
Currently, I get 
> fatal: [ds-sandbox-1708698094]: FAILED! => {"msg": "Failed to get information on remote file (/home/jupyter/entrypoint.py): sudo: a password is required\n"}

**Comment by ckunki** [comment]
The Ansible builtin-module `user` provides a [method](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#parameter-password) to specify the hash of a password.
So during creating of the user we need to provide this.

Next, we must [add this password](https://serverfault.com/questions/662443/running-ansible-task-as-a-specific-user) for tasks using Ansible's `become`: 
```
vars:
    ansible_become_pass: <Password of 'ubuntu' in OP's case>
```

To me this raises the follow-up question how we can pass the password to the Ansible script, then.
As embedding it into the Ansible files will make it public. :frowning_face:
